version: '3'

services: 
    app:
        container_name: base_app
        restart: always
        build: .
        ports: 
            - '80:5000'
        links: 
            - mongo
        environment:
            - "DB=${DB}"
            - "DB_NAME=${DB_NAME}"
            - "DB_APP_NAME=${DB_APP_NAME}"
            - "DB_PORT=${DB_PORT}"
            - "APP_PORT=${APP_PORT}"
        volumes:
            - "~/Public/BaseApp:/app:rw"
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
        volumes:
            - "~/Public/BaseApp/data:/data/db:rw"
